// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7OKwUITTTOp4X_Xo1CjYkAsJ2QZ-CiOY',
    appId: '1:36499263778:web:9748f5f18e5566b739d57b',
    messagingSenderId: '36499263778',
    projectId: 'upload-file-app-c49f5',
    authDomain: 'upload-file-app-c49f5.firebaseapp.com',
    storageBucket: 'upload-file-app-c49f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Z5JvkJSuSgIdLwcKSEIAZaFEmc6-LWA',
    appId: '1:36499263778:android:8df646873f5aefd339d57b',
    messagingSenderId: '36499263778',
    projectId: 'upload-file-app-c49f5',
    storageBucket: 'upload-file-app-c49f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKz2UL7DMuV5AVnzhWFKf6jd8G817XGJ8',
    appId: '1:36499263778:ios:de2af2153cdb371939d57b',
    messagingSenderId: '36499263778',
    projectId: 'upload-file-app-c49f5',
    storageBucket: 'upload-file-app-c49f5.appspot.com',
    iosClientId: '36499263778-5mehsdm7usk6v8j43p7dpa65fuv1lel8.apps.googleusercontent.com',
    iosBundleId: 'com.example.uploadFileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKz2UL7DMuV5AVnzhWFKf6jd8G817XGJ8',
    appId: '1:36499263778:ios:de2af2153cdb371939d57b',
    messagingSenderId: '36499263778',
    projectId: 'upload-file-app-c49f5',
    storageBucket: 'upload-file-app-c49f5.appspot.com',
    iosClientId: '36499263778-5mehsdm7usk6v8j43p7dpa65fuv1lel8.apps.googleusercontent.com',
    iosBundleId: 'com.example.uploadFileApp',
  );
}
